// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurrencyContract.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Google.Protobuf.currencies {
  public static class CurrencyService
  {
    static readonly string __ServiceName = "currencies.CurrencyService";

    static readonly Marshaller<global::Google.Protobuf.currencies.CurrenciesRequest> __Marshaller_CurrenciesRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.currencies.CurrenciesRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Protobuf.currencies.CurrenciesResponse> __Marshaller_CurrenciesResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.currencies.CurrenciesResponse.Parser.ParseFrom);

    static readonly Method<global::Google.Protobuf.currencies.CurrenciesRequest, global::Google.Protobuf.currencies.CurrenciesResponse> __Method_GetAll = new Method<global::Google.Protobuf.currencies.CurrenciesRequest, global::Google.Protobuf.currencies.CurrenciesResponse>(
        MethodType.Unary,
        __ServiceName,
        "GetAll",
        __Marshaller_CurrenciesRequest,
        __Marshaller_CurrenciesResponse);

    // service descriptor
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Protobuf.currencies.CurrencyContract.Descriptor.Services[0]; }
    }

    // client interface
    public interface ICurrencyServiceClient
    {
      global::Google.Protobuf.currencies.CurrenciesResponse GetAll(global::Google.Protobuf.currencies.CurrenciesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Google.Protobuf.currencies.CurrenciesResponse GetAll(global::Google.Protobuf.currencies.CurrenciesRequest request, CallOptions options);
      AsyncUnaryCall<global::Google.Protobuf.currencies.CurrenciesResponse> GetAllAsync(global::Google.Protobuf.currencies.CurrenciesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Google.Protobuf.currencies.CurrenciesResponse> GetAllAsync(global::Google.Protobuf.currencies.CurrenciesRequest request, CallOptions options);
    }

    // server-side interface
    public interface ICurrencyService
    {
      Task<global::Google.Protobuf.currencies.CurrenciesResponse> GetAll(global::Google.Protobuf.currencies.CurrenciesRequest request, ServerCallContext context);
    }

    // client stub
    public class CurrencyServiceClient : ClientBase, ICurrencyServiceClient
    {
      public CurrencyServiceClient(Channel channel) : base(channel)
      {
      }
      public global::Google.Protobuf.currencies.CurrenciesResponse GetAll(global::Google.Protobuf.currencies.CurrenciesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetAll, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Google.Protobuf.currencies.CurrenciesResponse GetAll(global::Google.Protobuf.currencies.CurrenciesRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_GetAll, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.currencies.CurrenciesResponse> GetAllAsync(global::Google.Protobuf.currencies.CurrenciesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetAll, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.currencies.CurrenciesResponse> GetAllAsync(global::Google.Protobuf.currencies.CurrenciesRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_GetAll, options);
        return Calls.AsyncUnaryCall(call, request);
      }
    }

    // creates service definition that can be registered with a server
    public static ServerServiceDefinition BindService(ICurrencyService serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder(__ServiceName)
          .AddMethod(__Method_GetAll, serviceImpl.GetAll).Build();
    }

    // creates a new client
    public static CurrencyServiceClient NewClient(Channel channel)
    {
      return new CurrencyServiceClient(channel);
    }

  }
}
#endregion
