// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductContract.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Google.Protobuf.Products {
  public static class ProductService
  {
    static readonly string __ServiceName = "products.ProductService";

    static readonly Marshaller<global::Google.Protobuf.Products.Product> __Marshaller_Product = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.Products.Product.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Protobuf.Products.ResultResponse> __Marshaller_ResultResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.Products.ResultResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Protobuf.Products.GetAllRequest> __Marshaller_GetAllRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.Products.GetAllRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Protobuf.Products.ProductsResponse> __Marshaller_ProductsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.Products.ProductsResponse.Parser.ParseFrom);

    static readonly Method<global::Google.Protobuf.Products.Product, global::Google.Protobuf.Products.ResultResponse> __Method_AddProduct = new Method<global::Google.Protobuf.Products.Product, global::Google.Protobuf.Products.ResultResponse>(
        MethodType.Unary,
        __ServiceName,
        "AddProduct",
        __Marshaller_Product,
        __Marshaller_ResultResponse);

    static readonly Method<global::Google.Protobuf.Products.Product, global::Google.Protobuf.Products.ResultResponse> __Method_UpdateProduct = new Method<global::Google.Protobuf.Products.Product, global::Google.Protobuf.Products.ResultResponse>(
        MethodType.Unary,
        __ServiceName,
        "UpdateProduct",
        __Marshaller_Product,
        __Marshaller_ResultResponse);

    static readonly Method<global::Google.Protobuf.Products.Product, global::Google.Protobuf.Products.ResultResponse> __Method_DeleteProduct = new Method<global::Google.Protobuf.Products.Product, global::Google.Protobuf.Products.ResultResponse>(
        MethodType.Unary,
        __ServiceName,
        "DeleteProduct",
        __Marshaller_Product,
        __Marshaller_ResultResponse);

    static readonly Method<global::Google.Protobuf.Products.GetAllRequest, global::Google.Protobuf.Products.ProductsResponse> __Method_GetAll = new Method<global::Google.Protobuf.Products.GetAllRequest, global::Google.Protobuf.Products.ProductsResponse>(
        MethodType.Unary,
        __ServiceName,
        "GetAll",
        __Marshaller_GetAllRequest,
        __Marshaller_ProductsResponse);

    // service descriptor
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Protobuf.Products.ProductContract.Descriptor.Services[0]; }
    }

    // client interface
    public interface IProductServiceClient
    {
      global::Google.Protobuf.Products.ResultResponse AddProduct(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Google.Protobuf.Products.ResultResponse AddProduct(global::Google.Protobuf.Products.Product request, CallOptions options);
      AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> AddProductAsync(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> AddProductAsync(global::Google.Protobuf.Products.Product request, CallOptions options);
      global::Google.Protobuf.Products.ResultResponse UpdateProduct(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Google.Protobuf.Products.ResultResponse UpdateProduct(global::Google.Protobuf.Products.Product request, CallOptions options);
      AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> UpdateProductAsync(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> UpdateProductAsync(global::Google.Protobuf.Products.Product request, CallOptions options);
      global::Google.Protobuf.Products.ResultResponse DeleteProduct(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Google.Protobuf.Products.ResultResponse DeleteProduct(global::Google.Protobuf.Products.Product request, CallOptions options);
      AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> DeleteProductAsync(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> DeleteProductAsync(global::Google.Protobuf.Products.Product request, CallOptions options);
      global::Google.Protobuf.Products.ProductsResponse GetAll(global::Google.Protobuf.Products.GetAllRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Google.Protobuf.Products.ProductsResponse GetAll(global::Google.Protobuf.Products.GetAllRequest request, CallOptions options);
      AsyncUnaryCall<global::Google.Protobuf.Products.ProductsResponse> GetAllAsync(global::Google.Protobuf.Products.GetAllRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Google.Protobuf.Products.ProductsResponse> GetAllAsync(global::Google.Protobuf.Products.GetAllRequest request, CallOptions options);
    }

    // server-side interface
    public interface IProductService
    {
      Task<global::Google.Protobuf.Products.ResultResponse> AddProduct(global::Google.Protobuf.Products.Product request, ServerCallContext context);
      Task<global::Google.Protobuf.Products.ResultResponse> UpdateProduct(global::Google.Protobuf.Products.Product request, ServerCallContext context);
      Task<global::Google.Protobuf.Products.ResultResponse> DeleteProduct(global::Google.Protobuf.Products.Product request, ServerCallContext context);
      Task<global::Google.Protobuf.Products.ProductsResponse> GetAll(global::Google.Protobuf.Products.GetAllRequest request, ServerCallContext context);
    }

    // client stub
    public class ProductServiceClient : ClientBase, IProductServiceClient
    {
      public ProductServiceClient(Channel channel) : base(channel)
      {
      }
      public global::Google.Protobuf.Products.ResultResponse AddProduct(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddProduct, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Google.Protobuf.Products.ResultResponse AddProduct(global::Google.Protobuf.Products.Product request, CallOptions options)
      {
        var call = CreateCall(__Method_AddProduct, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> AddProductAsync(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddProduct, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> AddProductAsync(global::Google.Protobuf.Products.Product request, CallOptions options)
      {
        var call = CreateCall(__Method_AddProduct, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Google.Protobuf.Products.ResultResponse UpdateProduct(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_UpdateProduct, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Google.Protobuf.Products.ResultResponse UpdateProduct(global::Google.Protobuf.Products.Product request, CallOptions options)
      {
        var call = CreateCall(__Method_UpdateProduct, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> UpdateProductAsync(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_UpdateProduct, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> UpdateProductAsync(global::Google.Protobuf.Products.Product request, CallOptions options)
      {
        var call = CreateCall(__Method_UpdateProduct, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Google.Protobuf.Products.ResultResponse DeleteProduct(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_DeleteProduct, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Google.Protobuf.Products.ResultResponse DeleteProduct(global::Google.Protobuf.Products.Product request, CallOptions options)
      {
        var call = CreateCall(__Method_DeleteProduct, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> DeleteProductAsync(global::Google.Protobuf.Products.Product request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_DeleteProduct, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.Products.ResultResponse> DeleteProductAsync(global::Google.Protobuf.Products.Product request, CallOptions options)
      {
        var call = CreateCall(__Method_DeleteProduct, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Google.Protobuf.Products.ProductsResponse GetAll(global::Google.Protobuf.Products.GetAllRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetAll, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Google.Protobuf.Products.ProductsResponse GetAll(global::Google.Protobuf.Products.GetAllRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_GetAll, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.Products.ProductsResponse> GetAllAsync(global::Google.Protobuf.Products.GetAllRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetAll, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Google.Protobuf.Products.ProductsResponse> GetAllAsync(global::Google.Protobuf.Products.GetAllRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_GetAll, options);
        return Calls.AsyncUnaryCall(call, request);
      }
    }

    // creates service definition that can be registered with a server
    public static ServerServiceDefinition BindService(IProductService serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder(__ServiceName)
          .AddMethod(__Method_AddProduct, serviceImpl.AddProduct)
          .AddMethod(__Method_UpdateProduct, serviceImpl.UpdateProduct)
          .AddMethod(__Method_DeleteProduct, serviceImpl.DeleteProduct)
          .AddMethod(__Method_GetAll, serviceImpl.GetAll).Build();
    }

    // creates a new client
    public static ProductServiceClient NewClient(Channel channel)
    {
      return new ProductServiceClient(channel);
    }

  }
}
#endregion
