// Code generated by protoc-gen-go.
// source: PurchaseContract.proto
// DO NOT EDIT!

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	PurchaseContract.proto

It has these top-level messages:
	Purchase
	PurchasesResponse
	ResultResponse
	GetAllRequest
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Status int32

const (
	Status_Ok     Status = 0
	Status_Failed Status = 1
)

var Status_name = map[int32]string{
	0: "Ok",
	1: "Failed",
}
var Status_value = map[string]int32{
	"Ok":     0,
	"Failed": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Purchase struct {
	Id         int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	FkCurrency int64 `protobuf:"varint,2,opt,name=FkCurrency" json:"FkCurrency,omitempty"`
}

func (m *Purchase) Reset()                    { *m = Purchase{} }
func (m *Purchase) String() string            { return proto.CompactTextString(m) }
func (*Purchase) ProtoMessage()               {}
func (*Purchase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PurchasesResponse struct {
	Purchases []*Purchase `protobuf:"bytes,1,rep,name=Purchases" json:"Purchases,omitempty"`
}

func (m *PurchasesResponse) Reset()                    { *m = PurchasesResponse{} }
func (m *PurchasesResponse) String() string            { return proto.CompactTextString(m) }
func (*PurchasesResponse) ProtoMessage()               {}
func (*PurchasesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PurchasesResponse) GetPurchases() []*Purchase {
	if m != nil {
		return m.Purchases
	}
	return nil
}

type ResultResponse struct {
	Status Status `protobuf:"varint,1,opt,name=Status,enum=services.Status" json:"Status,omitempty"`
}

func (m *ResultResponse) Reset()                    { *m = ResultResponse{} }
func (m *ResultResponse) String() string            { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()               {}
func (*ResultResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetAllRequest struct {
}

func (m *GetAllRequest) Reset()                    { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()               {}
func (*GetAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Purchase)(nil), "services.Purchase")
	proto.RegisterType((*PurchasesResponse)(nil), "services.PurchasesResponse")
	proto.RegisterType((*ResultResponse)(nil), "services.ResultResponse")
	proto.RegisterType((*GetAllRequest)(nil), "services.GetAllRequest")
	proto.RegisterEnum("services.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for PriceService service

type PriceServiceClient interface {
	Add(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error)
	Update(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error)
	Delete(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*PurchasesResponse, error)
}

type priceServiceClient struct {
	cc *grpc.ClientConn
}

func NewPriceServiceClient(cc *grpc.ClientConn) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) Add(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := grpc.Invoke(ctx, "/services.PriceService/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) Update(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := grpc.Invoke(ctx, "/services.PriceService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) Delete(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := grpc.Invoke(ctx, "/services.PriceService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*PurchasesResponse, error) {
	out := new(PurchasesResponse)
	err := grpc.Invoke(ctx, "/services.PriceService/GetAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PriceService service

type PriceServiceServer interface {
	Add(context.Context, *Purchase) (*ResultResponse, error)
	Update(context.Context, *Purchase) (*ResultResponse, error)
	Delete(context.Context, *Purchase) (*ResultResponse, error)
	GetAll(context.Context, *GetAllRequest) (*PurchasesResponse, error)
}

func RegisterPriceServiceServer(s *grpc.Server, srv PriceServiceServer) {
	s.RegisterService(&_PriceService_serviceDesc, srv)
}

func _PriceService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Purchase)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PriceServiceServer).Add(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _PriceService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Purchase)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PriceServiceServer).Update(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _PriceService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Purchase)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PriceServiceServer).Delete(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _PriceService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PriceServiceServer).GetAll(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _PriceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _PriceService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PriceService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PriceService_Delete_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _PriceService_GetAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0x87, 0x9b, 0x04, 0x42, 0xdf, 0x79, 0xb5, 0xc6, 0x3d, 0x68, 0xa8, 0x1e, 0x4a, 0x40, 0x28,
	0x3d, 0xec, 0x21, 0x22, 0x88, 0x20, 0x58, 0x2b, 0xad, 0x82, 0x60, 0x69, 0x11, 0xc1, 0xdb, 0x36,
	0x19, 0x6b, 0xe9, 0xda, 0x8d, 0xfb, 0x47, 0xf4, 0xeb, 0x78, 0xf4, 0x2b, 0x7a, 0x71, 0xdb, 0x90,
	0x84, 0xa2, 0xa7, 0x1e, 0xf7, 0xb7, 0xf3, 0x3c, 0x3b, 0xc3, 0x0e, 0xec, 0x0d, 0x8d, 0x4c, 0x9e,
	0x99, 0xc2, 0x9e, 0x58, 0x68, 0xc9, 0x12, 0x4d, 0x33, 0x29, 0xb4, 0x20, 0x75, 0x85, 0xf2, 0x6d,
	0x96, 0xa0, 0x8a, 0x3a, 0x50, 0x2f, 0x6a, 0x08, 0x80, 0x7b, 0x93, 0x86, 0x4e, 0xcb, 0x69, 0x7b,
	0xc4, 0x1e, 0xfa, 0xf3, 0x9e, 0x91, 0x12, 0x17, 0xc9, 0x47, 0xe8, 0x2e, 0xb3, 0xe8, 0x0c, 0x76,
	0x8b, 0x5a, 0x35, 0x42, 0x95, 0x89, 0x85, 0x85, 0x8e, 0xe0, 0x5f, 0x19, 0x5a, 0xd6, 0x6b, 0xff,
	0x8f, 0x09, 0x2d, 0xf4, 0xb4, 0xb8, 0x8a, 0x62, 0x68, 0x58, 0xc4, 0x70, 0x5d, 0x82, 0x2d, 0xf0,
	0xc7, 0x9a, 0x69, 0xa3, 0x56, 0x2f, 0x36, 0xe2, 0xa0, 0xa2, 0xf2, 0x3c, 0xda, 0x81, 0xed, 0x01,
	0xea, 0x2e, 0xe7, 0x23, 0x7c, 0x35, 0xa8, 0x74, 0xe7, 0xb0, 0x40, 0x88, 0x0f, 0xee, 0xdd, 0x3c,
	0xa8, 0xd9, 0x2e, 0xfd, 0x3e, 0x9b, 0x71, 0x4c, 0x03, 0x27, 0xfe, 0x76, 0x60, 0x6b, 0x28, 0xad,
	0x60, 0x9c, 0x7b, 0xc8, 0x09, 0x78, 0xdd, 0x34, 0x25, 0x7f, 0xb4, 0xd3, 0x0c, 0xab, 0x6c, 0xbd,
	0xad, 0xa8, 0x46, 0x4e, 0xc1, 0xbf, 0xcf, 0x52, 0xa6, 0x71, 0x13, 0xf2, 0x0a, 0x39, 0x6e, 0x40,
	0x5e, 0x80, 0x9f, 0x8f, 0x4a, 0xf6, 0xab, 0xaa, 0xb5, 0xe1, 0x9b, 0x07, 0xbf, 0x95, 0xaa, 0x32,
	0x5c, 0x9e, 0x43, 0x30, 0x13, 0x74, 0x2a, 0xb3, 0x84, 0xe2, 0x3b, 0x7b, 0xc9, 0x38, 0xaa, 0xc7,
	0xf2, 0x9b, 0x3f, 0x5d, 0xef, 0xfa, 0xf6, 0xe1, 0xcb, 0x0d, 0x07, 0x42, 0x4c, 0x39, 0xd2, 0xe1,
	0x72, 0x0b, 0x26, 0xe6, 0xa9, 0x54, 0x4e, 0xfc, 0xd5, 0x62, 0x1c, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x4d, 0x46, 0xd2, 0x70, 0x32, 0x02, 0x00, 0x00,
}
