// Code generated by protoc-gen-go.
// source: PurchaseContract.proto
// DO NOT EDIT!

/*
Package purchases is a generated protocol buffer package.

It is generated from these files:
	PurchaseContract.proto

It has these top-level messages:
	Purchase
	PurchasesResponse
	ResultResponse
	GetAllRequest
*/
package purchases

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Status int32

const (
	Status_Ok     Status = 0
	Status_Failed Status = 1
)

var Status_name = map[int32]string{
	0: "Ok",
	1: "Failed",
}
var Status_value = map[string]int32{
	"Ok":     0,
	"Failed": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Purchase struct {
	Id         int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	FkCurrency int64 `protobuf:"varint,2,opt,name=FkCurrency" json:"FkCurrency,omitempty"`
}

func (m *Purchase) Reset()                    { *m = Purchase{} }
func (m *Purchase) String() string            { return proto.CompactTextString(m) }
func (*Purchase) ProtoMessage()               {}
func (*Purchase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PurchasesResponse struct {
	Purchases []*Purchase `protobuf:"bytes,1,rep,name=Purchases" json:"Purchases,omitempty"`
}

func (m *PurchasesResponse) Reset()                    { *m = PurchasesResponse{} }
func (m *PurchasesResponse) String() string            { return proto.CompactTextString(m) }
func (*PurchasesResponse) ProtoMessage()               {}
func (*PurchasesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PurchasesResponse) GetPurchases() []*Purchase {
	if m != nil {
		return m.Purchases
	}
	return nil
}

type ResultResponse struct {
	Status Status `protobuf:"varint,1,opt,name=Status,enum=purchases.Status" json:"Status,omitempty"`
}

func (m *ResultResponse) Reset()                    { *m = ResultResponse{} }
func (m *ResultResponse) String() string            { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()               {}
func (*ResultResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetAllRequest struct {
}

func (m *GetAllRequest) Reset()                    { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()               {}
func (*GetAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Purchase)(nil), "purchases.Purchase")
	proto.RegisterType((*PurchasesResponse)(nil), "purchases.PurchasesResponse")
	proto.RegisterType((*ResultResponse)(nil), "purchases.ResultResponse")
	proto.RegisterType((*GetAllRequest)(nil), "purchases.GetAllRequest")
	proto.RegisterEnum("purchases.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for PurchaseService service

type PurchaseServiceClient interface {
	Add(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error)
	Update(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error)
	Delete(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*PurchasesResponse, error)
}

type purchaseServiceClient struct {
	cc *grpc.ClientConn
}

func NewPurchaseServiceClient(cc *grpc.ClientConn) PurchaseServiceClient {
	return &purchaseServiceClient{cc}
}

func (c *purchaseServiceClient) Add(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := grpc.Invoke(ctx, "/purchases.PurchaseService/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) Update(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := grpc.Invoke(ctx, "/purchases.PurchaseService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) Delete(ctx context.Context, in *Purchase, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := grpc.Invoke(ctx, "/purchases.PurchaseService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*PurchasesResponse, error) {
	out := new(PurchasesResponse)
	err := grpc.Invoke(ctx, "/purchases.PurchaseService/GetAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PurchaseService service

type PurchaseServiceServer interface {
	Add(context.Context, *Purchase) (*ResultResponse, error)
	Update(context.Context, *Purchase) (*ResultResponse, error)
	Delete(context.Context, *Purchase) (*ResultResponse, error)
	GetAll(context.Context, *GetAllRequest) (*PurchasesResponse, error)
}

func RegisterPurchaseServiceServer(s *grpc.Server, srv PurchaseServiceServer) {
	s.RegisterService(&_PurchaseService_serviceDesc, srv)
}

func _PurchaseService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Purchase)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PurchaseServiceServer).Add(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _PurchaseService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Purchase)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PurchaseServiceServer).Update(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _PurchaseService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Purchase)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PurchaseServiceServer).Delete(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _PurchaseService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PurchaseServiceServer).GetAll(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _PurchaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "purchases.PurchaseService",
	HandlerType: (*PurchaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _PurchaseService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PurchaseService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PurchaseService_Delete_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _PurchaseService_GetAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4a, 0x42, 0x41,
	0x14, 0xc6, 0xf5, 0x5e, 0x18, 0xf2, 0x44, 0xfe, 0x99, 0x20, 0x54, 0x5c, 0xd4, 0x5d, 0x84, 0xb8,
	0x98, 0x85, 0x2e, 0x82, 0x5a, 0x84, 0x1a, 0x5a, 0x10, 0x24, 0x4a, 0x04, 0xed, 0xc6, 0x7b, 0x4f,
	0x26, 0x4e, 0xce, 0x34, 0x7f, 0xa2, 0x5e, 0xa0, 0x07, 0x69, 0xd9, 0x53, 0x76, 0xd5, 0xae, 0x5e,
	0xc1, 0x95, 0xcb, 0xf9, 0xce, 0xf9, 0x7d, 0xe7, 0x9b, 0x99, 0x03, 0x27, 0x03, 0xa7, 0xc3, 0x57,
	0x6e, 0xb0, 0x2b, 0xe7, 0x56, 0xf3, 0xd0, 0x32, 0xa5, 0xa5, 0x95, 0x34, 0xa7, 0xfe, 0x75, 0x13,
	0x34, 0xe0, 0x20, 0x69, 0xa2, 0x00, 0xde, 0x5d, 0x54, 0xce, 0x9e, 0x66, 0xeb, 0x3e, 0x8d, 0x0f,
	0xbd, 0x59, 0xd7, 0x69, 0x8d, 0xf3, 0xf0, 0xab, 0xec, 0x2d, 0xb4, 0xe0, 0x0a, 0x4a, 0x49, 0xaf,
	0x19, 0xa2, 0x51, 0x72, 0x1e, 0x43, 0xe7, 0x90, 0x5b, 0x8b, 0x31, 0xeb, 0xd7, 0x0f, 0x9b, 0xc7,
	0x6c, 0xed, 0xcf, 0x92, 0x5a, 0xd0, 0x82, 0x7c, 0xcc, 0x38, 0x61, 0xd7, 0xe4, 0x19, 0x90, 0x91,
	0xe5, 0xd6, 0x99, 0xe5, 0xc8, 0x7c, 0xb3, 0x94, 0xc2, 0x56, 0x85, 0xa0, 0x00, 0x47, 0x7d, 0xb4,
	0x6d, 0x21, 0x86, 0xf8, 0xee, 0xd0, 0xd8, 0x46, 0x2d, 0x61, 0x28, 0x01, 0xef, 0x61, 0x56, 0xcc,
	0xc4, 0x39, 0x49, 0x8f, 0x4f, 0x05, 0x46, 0xc5, 0x6c, 0xf3, 0xdb, 0x83, 0x42, 0x32, 0x70, 0x84,
	0xfa, 0x63, 0x1a, 0x22, 0xbd, 0x00, 0xbf, 0x1d, 0x45, 0x74, 0x57, 0xa6, 0x6a, 0x25, 0x25, 0x6e,
	0x87, 0x0b, 0x32, 0xf4, 0x12, 0xc8, 0xa3, 0x8a, 0xb8, 0xc5, 0xfd, 0xd8, 0x1b, 0x14, 0xb8, 0x17,
	0xdb, 0x01, 0xb2, 0xba, 0x33, 0x2d, 0xa7, 0xda, 0xb6, 0x9e, 0xa1, 0x5a, 0xdb, 0xe1, 0x6a, 0x36,
	0x1e, 0x9d, 0x6b, 0x28, 0x4e, 0x25, 0x9b, 0x68, 0x15, 0x32, 0xfc, 0xe4, 0x6f, 0x4a, 0xa0, 0x79,
	0xde, 0x7c, 0xfa, 0x8f, 0xe7, 0xdf, 0xde, 0x3f, 0xfd, 0x7a, 0x95, 0xbe, 0x94, 0x13, 0x81, 0x6c,
	0xb0, 0x58, 0x8a, 0xb1, 0x7b, 0xd9, 0x98, 0x8e, 0xc9, 0x72, 0x51, 0x5a, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xb5, 0x01, 0xfd, 0x93, 0x42, 0x02, 0x00, 0x00,
}
